# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2017-02-18 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hear1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
